export const DELIVERY_LIST_REQUEST = "DELIVERY_LIST_REQUEST";
export const DELIVERY_LIST_SUCCESS = "DELIVERY_LIST_SUCCESS";
export const DELIVERY_LIST_FAIL = "DELIVERY_LIST_FAIL";

export const DELIVERY_EDIT_REQUEST = "DELIVERY_EDIT_REQUEST";
export const DELIVERY_EDIT_SUCCESS = "DELIVERY_EDIT_SUCCESS";
export const DELIVERY_EDIT_FAIL = "DELIVERY_EDIT_FAIL";

export const DELIVERY_DELETE_REQUEST = "DELIVERY_DELETE_REQUEST";
export const DELIVERY_DELETE_SUCCESS = "DELIVERY_DELETE_SUCCESS";
export const DELIVERY_DELETE_FAIL = "DELIVERY_DELETE_FAIL";

export const DELIVERY_CREATE_REQUEST = "DELIVERY_CREATE_REQUEST";
export const DELIVERY_CREATE_SUCCESS = "DELIVERY_CREATE_SUCCESS";
export const DELIVERY_CREATE_FAIL = "DELIVERY_CREATE_FAIL";
export const DELIVERY_CREATE_RESET = "DELIVERY_CREATE_RESET";

export const DELIVERY_UPDATE_REQUEST = "DELIVERY_UPDATE_REQUEST";
export const DELIVERY_UPDATE_SUCCESS = "DELIVERY_UPDATE_SUCCESS";
export const DELIVERY_UPDATE_FAIL = "DELIVERY_UPDATE_FAIL";
export const DELIVERY_UPDATE_RESET = "DELIVERY_UPDATE_RESET";

export const DELIVERY_DETAILS_REQUEST = "DELIVERY_DETAILS_REQUEST";
export const DELIVERY_DETAILS_SUCCESS = "DELIVERY_DETAILS_SUCCESS";
export const DELIVERY_DETAILS_FAIL = "DELIVERY_DETAILS_FAIL";